version: "3.8"
services:
    jupyter-server:
        image: cpu-jupyter
        init: true
        build:
            context: ./
            dockerfile: cpu-jupyter.Dockerfile
        env_file: ./.env
        ports:
            - ${JUPYTER_PORT}:${JUPYTER_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "jupyter",
                "notebook",
                "--ip=*",
                "--port=${JUPYTER_PORT}",
                "--allow-root",
                "--notebook-dir=${JUPYTER_DIR}",
                '--NotebookApp.token=${JUPYTER_TOKEN}'
            ]


    tensorboard:
        image: monitoring
        build:
            context: ./
            dockerfile: monitoring.Dockerfile
        ports:
            - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "tensorboard",
                "--logdir=${TENSORBOARD_DIR}",
                "--port=${TENSORBOARD_PORT}",
                "--bind_all",
            ]